# Generated by Django 4.1.4 on 2023-01-12 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
