# Generated by Django 4.1.4 on 2023-01-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_alter_comment_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='C:\\Users\\J Suarez\\Documents\\PROYECTO_ISW\\proyectoISW\\foro\\static\\img\\new_user.png', upload_to=''),
        ),
    ]
